### ISSUE TITLE
Mail and Discord Alert Action not triggering

### ISSUE THREAD

**Issue by DavidVarosoGomesCPNV** [CPNV-MON1/Pandora#3]
Les mails qui devraient s'envoyer lors-ce que une alerte ce trigger. Fonctionne en local mais pas sur AWS pour une raison inconnue.
Le mail de test fonctionne parfaitement et l'adresse mail indiquée pour l'envoi des mail d'alerte est la même, le problème n'est donc pas lié au SNMP.

Image exemple du mail qui fonctionne en local, mail test, log exchange de la connexion smtp réussie

![3](https://github.com/CPNV-MON1/Pandora/assets/48351164/aa433bc1-3ab5-4fcc-91ad-aace4e4d7963)
![1](https://github.com/CPNV-MON1/Pandora/assets/48351164/249cbfb2-95a9-418a-abb6-c85911573ccc)
![2](https://github.com/CPNV-MON1/Pandora/assets/48351164/68c0ab0f-8a9b-44f8-ba04-7cced28fd4bf)

**Comment by DavidVarosoGomesCPNV** [comment]
Problème similaire avec l'alerte discord, sur la machine de test locale la configuration fonctionne comme desiré.

Alerte d'état critique 
![image](https://github.com/CPNV-MON1/Pandora/assets/48351164/ea5f4531-5f34-446a-9d9d-c5fb2e9924c0)

Alerte de retour au normal
![image](https://github.com/CPNV-MON1/Pandora/assets/48351164/c5485b83-97f8-43c2-8fd8-4cd08a0915ac)

La même configuration ne fonctionne pas sur AWS.
Comme pour les mails, les alertes discord de test de base et de l'API fonctionnent.
![image](https://github.com/CPNV-MON1/Pandora/assets/48351164/0a9c7c5a-3455-4b32-b36a-84bb6c8ee96e)

**Comment by DavidVarosoGomesCPNV** [comment]
A faire - Chercher les log du serveur voir si il y a quelque chose

**Comment by NicolasGlassey** [comment]
@DavidVarosoGomesCPNV 

Je viens de lire votre issue.

Sur votre machine locale, avez-vous installé pandora à l'aide d'un super user utilisant sudo, où êtes-vous en root en permanence ?

**Comment by DavidVarosoGomesCPNV** [comment]
@NicolasGlassey 

J'ai un user avec sudo mais c'est pas impossible que j'ai fait l'install avec root, si j'ai le temps après le travail que je dois faire sur d'autres modules je peux essayer ça.

**Comment by NicolasGlassey** [comment]
@DavidVarosoGomesCPNV  Il faudrait réussir à détecter le log qui mentionne que l'événement et l'action ont été réalisé chez vous en lcoal, et voir à quelle étape sur AWS cela plante.

J'exclu pour l'instant un souci en lien avec l'infra AWS, mais suppose que la limitation vient des droits avec lequelles votre serveur de monitoring exécute les processus sur l'OS.

**Comment by DavidVarosoGomesCPNV** [comment]
Problems solved, documented on the wiki
